services:
  dabi-stream-brain:
    build:
      context: .
      dockerfile: dabi-stream-brain/Dockerfile
    restart: unless-stopped
    env_file: .env
    environment:
      RABBITMQ_URL: amqp://overlay:strongpassword@rabbitmq:5672/
    networks:
      - twitchbroadcaster_net
    volumes:
      - ./dabi-stream-brain:/app
      - ./shared:/app/shared

  dabi-discord:
    build:
      context: .
      dockerfile: dabi-stream-brain/Dockerfile
    restart: unless-stopped
    env_file: .env
    environment:
      RABBITMQ_URL: amqp://overlay:strongpassword@rabbitmq:5672/
    networks:
      - twitchbroadcaster_net
    volumes:
      - ./dabi-stream-brain:/app
      - ./shared:/app/shared
    command: python discord_bot.py

  dabi-chatroom-brain:
    build:
      context: .
      dockerfile: dabi-chatroom-brain/Dockerfile
    restart: unless-stopped
    env_file: .env
    environment:
      RABBITMQ_URL: amqp://overlay:strongpassword@rabbitmq:5672/
    networks:
      - twitchbroadcaster_net
    volumes:
      - ./dabi-chatroom-brain:/app
      - ./shared:/app/shared

networks:
  twitchbroadcaster_net:
    external: true
